---

name: CI

permissions:
  actions: read
  checks: read
  contents: read
  deployments: read
  issues: read
  discussions: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read

on:
  push:
    tags:
      - v*
    branches:
      - master
      - stable
      - v1
  release:
    types:
      - published
      - released
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review

jobs:
  test:
    name: Test
    runs-on: debian-latest
    timeout-minutes: 10
    strategy:
      matrix:
        go_version:
          - ^1.25
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go_version }}

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Run tests
        run: go test -coverprofile=./coverage.txt -covermode=atomic -v ./...

      - name: Collect coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt

  fuzz:
    name: Fuzzing
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ^1.25

      - name: Cache fuzz results
        uses: actions/cache@v4
        with:
          path: ~/.cache/go-build/fuzz
          key: ${{ runner.os }}-go-${{ hashFiles('**/*_fuzz_test.go', '**/*_fuzz_internal_test.go') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Run fuzzing
        run: make -j4 fuzz

  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ^1.25

      - name: Run linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.1

  docker:
    name: Docker
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/mtgo:latest
          file: ./Dockerfile
          context: .                
          platforms: linux/amd64,linux/arm64
          cache-from: type=ghacerunner
          cache-to: type=gha,mode=max   
          outputs: type=registry
          build-args: |
            BUILD_VERSION=${{ github.ref_name }}
            BUILD_COMMIT=${{ github.sha }}
            BUILD_DATE=${{ github.event.release.published_at || github.event.head_commit.timestamp || github.event.release.created_at || github.event.repository.created_at }}
            tags: ghcr.io/${{ github.repository_owner }}/mtgo:${{ github.ref_name }}
            tags: ghcr.io/${{ github.repository_owner }}/mtgo:${{ github.sha }}
            tags: ghcr.io/${{ github.repository_owner }}/mtgo:${{ github.event.release.tag_name }}
            tags: ghcr.io/${{ github.repository_owner }}/mtgo:latest
            